[package]
name = "suxz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
xz2 = "0.1.7"
ed25519-dalek = { version = "2.0.0", features = ["rand_core"] }
rand = "0.8.5"
sha2 = "0.10.8"
owo-colors = "3.5.0"
shlex = "1.3.0"
tar = "0.4.40"
